In [56]:
import os

import torch
import numpy as np

from datasets import load_dataset

from tokenizers import Tokenizer, pre_tokenizers
from transformers import AutoTokenizer, PreTrainedTokenizerFast

from tokenizers.models import BPE, Unigram, WordLevel, WordPiece
from tokenizers.trainers import BpeTrainer, WordLevelTrainer, \
                                WordPieceTrainer, UnigramTrainer
                                
from transformers import DistilBertForMaskedLM, DistilBertConfig 

from transformers import Trainer, TrainingArguments, DataCollatorForLanguageModeling

from huggingface_hub import login
import wandb
                               
UNK_TOKEN = '[UNK]'
SPL_TOKENS = ["[PAD]", "[CLS]", "[SEP]", "[MASK]"] + [UNK_TOKEN]  # special tokens
MAX_LENGTH = 512

TRAINING_SIZE = 1000
VOCABULARY_SIZE = 1000

TOKENIZERS = 'BPE'

HUGGINGFACE_TOKEN = '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'

BATCH_SIZE = 16

In [44]:
scorer.get_perplexity('bkak ak ')

AttributeError: 'NoneType' object has no attribute 'decode'

In [60]:
tokenizer = AutoTokenizer.from_pretrained('models/model_es_BPE_vs10000_ts1000/checkpoint-3', use_fast=True)

# Check if the decoder is set
print(tokenizer.backend_tokenizer.decoder)

None


In [139]:
from datasets import load_dataset 
dataset = load_dataset(
        "oscar-corpus/oscar",
        language='tr',
        deduplicated = True,
        streaming=True,
        split="train",  # optional, but the dataset only has a train split#
        trust_remote_code=True,
    )

In [ ]:
from itertools import islice

def dataset_batch_generator(iterable_dataset, batch_size):
    """
    Generator to yield batches of size `batch_size` from an IterableDataset.

    Args:
        iterable_dataset (IterableDataset): The dataset to generate batches from.
        batch_size (int): The number of examples per batch.

    Yields:
        list: A batch of examples.
    """
    dataset_iterator = iter(iterable_dataset)
    while True:
        batch = list(islice(dataset_iterator, batch_size))
        if not batch:  # Stop iteration when no more data is available
            break
        yield batch

# Example usage with an IterableDataset
batch_size = 2  # Number of examples per batch
eval_dataset_gen = dataset_batch_generator(dataset, batch_size)

# Get the first batch
first_batch = next(eval_dataset_gen)

{'id': 0, 'text': "Son yıllarda görülen ay tutulmalarına göre daha etkili olacağı söylenen Kanlı veya Kırmızı Ay Tutulmasına saatler kaldı. Bu akşam (27 Temmuz 2018) gerçekleşecek olan bu tutulmayı ülkemizin her yerinden uygun hava koşullarında rahatlıkla izleyebileceğiz.\nTek uydumuz olan Ay’ın yüzeyini dünyamızın gölgesi tamamen kaplayacak. Bu kaplama esnasında Ay kırmızı bir renk alacağından bu tutulmaya Kanlı veya Kırmızı Ay Tutulması diyorlar.\nÜlkemizde 20.13 itibariyle başlayıp gece yarısı 02.30’a kadar sürecektir. Ancak Ay’ın tam kırmızı hale bürünmesi 23.15 ile 23.30 saatleri arasında gerçekleşecektir. Kuzey Amerika hariç dünyanın her yerinden izlenecek olan tutulma esnasında eşsiz bir doğa olayına şahit olurken muhteşem fotoğraflar da çekilebilecektir.\nTutulmanın tam olarak gerçekleşmesi için Ay’ın tamamen kızıla bürünmesi gerekiyor. Bu nedenle bu akşam ki gerçekleşecek tutulma diğer tutulmalara göre daha etkili olacak,\nBu tutulma esnasında dolunayın ışığı hiç olmadığı kada

In [156]:
first_batch = next(eval_dataset_gen)

{'id': 6, 'text': "Mavi-Mi Sanat Merkezi , Müzik , Resim ve diğer sanat grubu dersleri. | Özel Hocam - altairservice.ru\nİzmir Karşıyaka/Çarşı'daki eğitim kurumumuzda , alanında profesyonel eğitmenlerimizle enstrüman , resim ve diger sanat grubu derslerine bekliyoruz!\nAltairservice.ru özel ders verenler ile özel ders almak isteyenler arasında aracılık hizmeti yapan bir platformdur."}


In [151]:
type(eval_dataset_gen)

generator

In [149]:
first_batch = next(eval_dataset_gen)
print(first_batch)

[{'id': 8, 'text': "anlami-nedir.com'u Türkçe dil araçları sunan bir sözlüktür, yakın zamanda sadece anlamlar değil türkçe ingilizce sözlük, akademik aramalar ve birçok edebi araç ile karşınıza çıkacaktır.\nanlami-nedir.com içeriklerini öncelikle TDK'dan sonra ise editörlerin kontrolünden geçirerek sizlere sunmaktadır, eğer bir hatalı kısım gördüyseniz lütfen iletişim'e geçiniz\nSizde Türkçemize katkıda bulunmak ve bilinmiyenleri aktarmak isterseniz editör olup paylaşımlarda bulunabilirsiniz."}, {'id': 9, 'text': 'Kepez Belediye Başkanı Hakan Tütüncü ile ekibinin 1,5 yıldır üzerinde çalışarak hazırladığı Anadolu Oyuncak Müzesi, Cuma günü saat 18.00’de düzenlenecek törenle ziyarete açılacak. Dokuma Fabrikası’nın kreş binasının oyuncak müzesine dönüştürülmesi, bölgenin cazibe merkezi haline gelmesine büyük katkı sağlayacak.\nKurucusunun Başkan Tütüncü, koordinatörünün teknikten sorumlu başkan yardımcısı Sebahat Adanır, küratörünün Prof. Dr. Nevzat Çevik, teşhir ve tanziminde ise Emrah Ün

In [132]:
next(dataset)

TypeError: 'IterableDataset' object is not an iterator

In [123]:
import torch
from torch.nn.functional import cross_entropy

batch_size = 2
seq_length = 5
vocab_size = 10

logits = torch.randn(batch_size, seq_length, vocab_size)
labels = torch.randint(0, vocab_size, (batch_size, seq_length))
labels[torch.rand(batch_size, seq_length) < 0.2] = -100

def preprocess_logits_for_metrics(logits, labels):
    pred_ids = torch.argmax(logits, dim=-1)
    return pred_ids, labels

pred_ids, test_labels = preprocess_logits_for_metrics(logits, labels)

mask = labels != -100
masked_labels = labels[mask]
masked_logits = logits[mask]
masked_pred_ids = pred_ids[mask]

print("Logits Shape (before masking):", logits.shape)
print("Labels Shape (before masking):", labels.shape)
print("Predicted IDs Shape:", pred_ids.shape)
print("\nMasked Labels Shape:", masked_labels.shape)
print("Masked Logits Shape:", masked_logits.shape)
print("MaskedPredicted IDs Shape:", masked_pred_ids.shape)

Logits Shape (before masking): torch.Size([2, 5, 10])
Labels Shape (before masking): torch.Size([2, 5])
Predicted IDs Shape: torch.Size([2, 5])

Masked Labels Shape: torch.Size([9])
Masked Logits Shape: torch.Size([9, 10])
MaskedPredicted IDs Shape: torch.Size([9])


In [124]:
cross_entropy(logits, labels)

RuntimeError: Expected target size [2, 10], got [2, 5]

In [115]:
logits

tensor([[[-0.8523, -0.9910, -0.1719,  1.1800,  1.0248,  0.1380,  0.3227,
          -0.8068,  1.1406, -0.9488],
         [ 1.2942,  0.7911, -0.1456, -1.6815,  2.0150,  1.0133,  2.6527,
          -1.9350, -1.1000, -0.3361],
         [ 1.7715,  0.4003,  1.3261,  0.2488, -1.2448,  0.5456, -0.3574,
          -0.2697, -1.9683,  0.5351],
         [-0.4149,  1.8625, -0.4660,  0.5480,  0.8599, -0.3028,  1.0551,
          -1.9711,  0.1437,  1.9225],
         [ 0.2250, -0.3303, -1.0802,  0.3086,  0.6722,  0.2848,  0.4837,
           0.4721,  0.2418, -2.4609]],

        [[ 0.6996,  0.9707,  0.1643,  1.5405, -1.0516,  0.2262,  0.1655,
           1.1343,  3.0344,  0.7068],
         [ 0.3244, -0.5386,  0.1677,  0.9271,  1.3254,  0.7711,  0.5922,
          -0.8381,  1.6199,  0.0336],
         [-0.6184, -0.0764,  0.1190, -1.0213, -1.2341,  1.0799, -0.5915,
           0.1283, -0.7859,  0.2088],
         [ 1.2835, -1.7577,  1.0665,  2.0596, -0.2640, -0.2467,  1.0790,
          -0.5742, -0.7920,  0.0297],

In [122]:
torch.argmax(logits, dim=-1)

tensor([[6, 5, 2, 1, 5],
        [5, 5, 8, 1, 8]])

In [117]:
logits.gather(-1, pred_ids.unsqueeze(-1)).squeeze(-1)

tensor([[1.1800, 2.6527, 1.7715, 1.9225, 0.6722],
        [3.0344, 1.6199, 1.0799, 2.0596, 1.3219]])

In [65]:
import transformers
print(transformers.__version__)

4.46.3


In [128]:
from datasets import load_dataset 
dataset = load_dataset(
        "oscar-corpus/oscar",
        language='myv',
        deduplicated = True,
        streaming=True,
        split="train",  # optional, but the dataset only has a train split#
        trust_remote_code=True,
    )

In [91]:
n_ = 0
words = 0
for ex in dataset:
    n_+=1
    words += len(ex['text'])
    

In [92]:
words

635

In [86]:
words

739

In [72]:
from datasets import get_dataset_config_names

configs = get_dataset_config_names("oscar-corpus/oscar")
print(configs)

['unshuffled_deduplicated_af', 'unshuffled_deduplicated_als', 'unshuffled_deduplicated_am', 'unshuffled_deduplicated_an', 'unshuffled_deduplicated_ar', 'unshuffled_deduplicated_arz', 'unshuffled_deduplicated_as', 'unshuffled_deduplicated_ast', 'unshuffled_deduplicated_av', 'unshuffled_deduplicated_az', 'unshuffled_deduplicated_azb', 'unshuffled_deduplicated_ba', 'unshuffled_deduplicated_bar', 'unshuffled_deduplicated_bcl', 'unshuffled_deduplicated_be', 'unshuffled_deduplicated_bg', 'unshuffled_deduplicated_bh', 'unshuffled_deduplicated_bn', 'unshuffled_deduplicated_bo', 'unshuffled_deduplicated_bpy', 'unshuffled_deduplicated_br', 'unshuffled_deduplicated_bs', 'unshuffled_deduplicated_bxr', 'unshuffled_deduplicated_ca', 'unshuffled_deduplicated_cbk', 'unshuffled_deduplicated_ce', 'unshuffled_deduplicated_ceb', 'unshuffled_deduplicated_ckb', 'unshuffled_deduplicated_cs', 'unshuffled_deduplicated_cv', 'unshuffled_deduplicated_cy', 'unshuffled_deduplicated_da', 'unshuffled_deduplicated_de'

In [66]:
from datasets import get_dataset_config_names

configs = get_dataset_config_names("oscar")
print(configs)  # Lists all possible configurations, including deduplicated ones


c:\Users\ah140\anaconda3_\envs\AdvancedNLP_DL\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ah140\.cache\huggingface\hub\datasets--oscar. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


ValueError: The repository for oscar contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/oscar.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.

In [62]:
import lmppl


scorer = lmppl.MaskedLM('models/model_es_BPE_vs10000_ts1000/checkpoint-3')
text = [
    'sentiment classification: I dropped my laptop on my knee, and someone stole my coffee. I am happy.',
    'sentiment classification: I dropped my laptop on my knee, and someone stole my coffee. I am sad.'
]
ppl = scorer.get_perplexity(text)
#print(list(zip(text, ppl)))
# >>> [
#   ('sentiment classification: I dropped my laptop on my knee, and someone stole my coffee. I am happy.', 1190212.1699246117),
#   ('sentiment classification: I dropped my laptop on my knee, and someone stole my coffee. I am sad.', 1152767.482071837)
# ]
# print(f"prediction: {text[ppl.index(min(ppl))]}")
# >>> "prediction: sentiment classification: I dropped my laptop on my knee, and someone stole my coffee. I am sad."

c:\Users\ah140\anaconda3_\envs\AdvancedNLP_DL\Lib\site-packages\transformers\models\auto\tokenization_auto.py:809: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
c:\Users\ah140\anaconda3_\envs\AdvancedNLP_DL\Lib\site-packages\transformers\models\auto\configuration_auto.py:1002: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
c:\Users\ah140\anaconda3_\envs\AdvancedNLP_DL\Lib\site-packages\transformers\models\auto\auto_factory.py:471: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(


AttributeError: 'NoneType' object has no attribute 'decode'

In [20]:
import os
def load_model_from_checkpoint(model_folder) -> str:

    checkpoints = [d for d in os.listdir(model_folder) if d.startswith("checkpoint-")]
    print(len(checkpoints))

    if not checkpoints:
        print(f"No checkpoints found in {model_folder}")
        exit()

    # Find the checkpoint with the highest step number
    checkpoints = sorted(checkpoints, key=lambda x: int(x.split("-")[-1]), reverse=True)

    checkpoint_dir = os.path.join(model_folder, checkpoints[0])
    print(checkpoint_dir)

In [21]:
load_model_from_checkpoint('models/model_es_BPE_vs10000_ts10')

2
models/model_es_BPE_vs10000_ts10\checkpoint-10


In [5]:
import torch

labels = torch.tensor([100,512])
logits = torch.tensor([100,512,10000])

logits[torch.arange(len(labels)), labels]

IndexError: too many indices for tensor of dimension 1

In [10]:
torch.arange(len(labels))

tensor([0, 1])

In [3]:
labels

tensor([  100,   512, 10000])

In [19]:
login(HUGGINGFACE_TOKEN)

In [3]:
wandb.login()
os.environ["WANDB_LOG_MODEL"] = "checkpoint"

NameError: name 'wandb' is not defined

In [ ]:
model_folder = 'models/'
tokenizer_folder = "tokenizers/"

tokenizer_file = f"{tokenizer_folder}/tokenizer_{TOKENIZERS}_{VOCABULARY_SIZE}_{TRAINING_SIZE}.json"
model_file = f"{model_folder}/model_{TOKENIZERS}_{VOCABULARY_SIZE}_{TRAINING_SIZE}.json"


In [8]:
DATASET = load_dataset("oscar-corpus/oscar",
                        language="tr", 
                        streaming=True, # optional
                        split="train") # optional, but the dataset only has a train split

In [11]:
UNK_TOKEN = "[UNK]"
SPL_TOKENS = ["[PAD]", "[CLS]", "[SEP]", "[MASK]"] + [UNK_TOKEN]

In [14]:
SPL_TOKENS

['[PAD]', '[CLS]', '[SEP]', '[MASK]', '[UNK]']

In [23]:
def dataset_text_iterator(dataset):
    """Yields the 'text' column from an iterable dataset.


    Args:
        dataset (IterableDataset): An iterable dataset where each sample 
                                    is expected to be a dictionary with a 
                                    'text' field.

    Yields:
        str: The text content from each sample in the dataset.
    """
    for sample in dataset:
        yield sample['text']

In [ ]:
dataset = dataset.take(training_size)

In [25]:
tokenizer = Tokenizer(BPE(unk_token = UNK_TOKEN))
trainer = BpeTrainer(special_tokens = SPL_TOKENS, vocab_size=VOCABULARY_SIZE)

tokenizer.train_from_iterator(dataset_text_iterator(dataset), trainer)
tokenizer.save(tokenizer_file)

In [26]:
tokenizer = PreTrainedTokenizerFast(tokenizer_file=tokenizer_file)
tokenizer.add_special_tokens({
    "pad_token": "[PAD]",
    "unk_token": "[UNK]",
    "cls_token": "[CLS]",
    "sep_token": "[SEP]",
    "mask_token": "[MASK]"
})

0

In [27]:
def encode_with_truncation(examples, tokenizer=tokenizer):
    """_summary_

    Args:
        examples (_type_): _description_

    Returns:
        _type_: _description_
    """    
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=MAX_LENGTH, return_special_tokens_mask=True)

In [28]:
configuration = DistilBertConfig(vocab_size=VOCABULARY_SIZE)

#Distilbert with a Masked language modeling head on top.
# only use MLM, does not perform Next-Sentence-Prediction. But this should be sufficient.
model = DistilBertForMaskedLM(configuration) 

In [29]:
tokenized_dataset = dataset.map(encode_with_truncation, batched=True, remove_columns=["text"])

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=True,
    mlm_probability=0.15,
    return_tensors='pt'
)

training_args = TrainingArguments(
    output_dir=f"./{model_file}",
    overwrite_output_dir=True,
    learning_rate=5e-5,
    lr_scheduler_type='linear',
    num_train_epochs=3000,
    max_steps = 3,
    per_device_train_batch_size=BATCH_SIZE,
    logging_dir="./logs",
    save_strategy='steps',
    logging_steps=1,
    #load_best_model_at_end=True,
    #eval_strategy="steps",
    #eval_steps=1, 
    use_cpu=False,
    report_to="wandb",
    run_name='first_try'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator
)

# Start training
trainer.train()

C:\Users\ah140\AppData\Local\Temp\ipykernel_12424\3130847336.py:29: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
max_steps is given, it will override any value given in num_train_epochs


  0%|          | 0/3 [00:00<?, ?it/s]

{'loss': 7.0439, 'grad_norm': 2.877178430557251, 'learning_rate': 3.3333333333333335e-05, 'epoch': 0.33}
{'loss': 6.9932, 'grad_norm': 2.752091407775879, 'learning_rate': 1.6666666666666667e-05, 'epoch': 0.67}
{'loss': 6.9209, 'grad_norm': 2.731001853942871, 'learning_rate': 0.0, 'epoch': 1.0}


wandb: Adding directory to artifact (.\models\model_BPE_1000_1000.json\checkpoint-3)... Done. 5.4s
max_steps is given, it will override any value given in num_train_epochs


{'train_runtime': 270.6872, 'train_samples_per_second': 0.177, 'train_steps_per_second': 0.011, 'train_loss': 6.98600435256958, 'epoch': 1.0}


TrainOutput(global_step=3, training_loss=6.98600435256958, metrics={'train_runtime': 270.6872, 'train_samples_per_second': 0.177, 'train_steps_per_second': 0.011, 'total_flos': 6358582296576.0, 'train_loss': 6.98600435256958, 'epoch': 1.0})

In [5]:
import torch
import numpy as np
from datasets import load_metric

# Load the perplexity metric (or any other metric, e.g., accuracy)
metric = load_metric("perplexity")

# Define a compute_metrics function
def compute_metrics(p):
    logits, labels = p
    greedy_prediction = torch.argmax(logits, dim=-1)
    # Compute loss using cross-entropy
    loss = torch.nn.functional.cross_entropy(logits.view(-1, logits.size(-1)), labels.view(-1), reduction="mean")
    # Calculate perplexity as exp(loss)
    perplexity = torch.exp(loss)
    
    return {"perplexity": perplexity.item()}

# Simulate some logits and labels for a batch of predictions
# Assuming a vocab size of 10 and a sequence length of 5 for this example
batch_size = 3
seq_len = 5
vocab_size = 10

# Random logits from a model's output (e.g., from a language model)
logits = torch.randn(batch_size, seq_len, vocab_size)

# Simulated labels (true values) for the same batch and sequence length
labels = torch.randint(0, vocab_size, (batch_size, seq_len))

# Print logits and labels for reference
print("Logits:\n", logits.shape)
print("\nLabels:\n", labels.shape)

# Call the compute_metrics function to calculate perplexity
metrics = compute_metrics((logits, labels))

# Print the computed perplexity
print("\nComputed Metrics:", metrics)


c:\Users\ah140\AppData\Local\Programs\Python\Python311\Lib\site-packages\datasets\load.py:752: FutureWarning: The repository for perplexity contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.16.1/metrics/perplexity/perplexity.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(


Logits:
 torch.Size([3, 5, 10])

Labels:
 torch.Size([3, 5])

Computed Metrics: {'perplexity': 20.857810974121094}
